import type { Prompt } from '../types';

export const viralPrompts: Prompt[] = [
  {
    id: 'viral-001',
    promptText: 'Create a cinematic film still of a character in the style of Studio Ghibli, featuring lush, hand-painted backgrounds, soft lighting, and a sense of wonder. The character should be looking out over a fantastical landscape.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Instagram',
    country: 'Global',
    trendingDate: '2023-05-15',
    tags: ['ghibli', 'anime', 'cinematic', 'illustration'],
  },
  {
    id: 'viral-002',
    promptText: 'Generate an image of a confident Indian woman wearing a beautiful, intricate traditional saree, standing in a futuristic cityscape. The style should be hyperrealistic with a focus on fabric detail and lighting.',
    category: 'Viral Trends',
    targetModel: 'Gemini',
    platform: 'Instagram',
    country: 'India',
    trendingDate: '2024-03-20',
    tags: ['saree', 'hyperrealistic', 'fashion', 'futurism'],
  },
  {
    id: 'viral-003',
    promptText: 'A short video of a mundane daily activity (like making coffee) shot in the style of a Wes Anderson film. Use symmetrical framing, a distinct pastel color palette, quirky deadpan narration, and a vintage font for titles.',
    category: 'Viral Trends',
    targetModel: 'Veo',
    platform: 'TikTok',
    country: 'USA',
    trendingDate: '2023-08-10',
    tags: ['wes anderson', 'cinematic', 'aesthetic', 'short film'],
  },
  {
    id: 'viral-004',
    promptText: 'Create a movie poster for an imaginary Pixar film titled "The Last Firefly". The poster should feature a cute, determined firefly character against a magical, glowing forest backdrop. Use the typical Pixar 3D animated style with expressive characters.',
    category: 'Viral Trends',
    targetModel: 'DALL-E 3',
    platform: 'Reddit',
    country: 'Global',
    trendingDate: '2023-11-05',
    tags: ['pixar', 'movie poster', '3d render', 'character design'],
  },
  {
    id: 'viral-005',
    promptText: 'A photograph of me as a character in the Barbie movie. I am wearing a vibrant pink outfit, have perfectly styled hair, and am standing in a dreamy, pastel-colored Barbie world. The style should be glossy and high-fashion.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Instagram',
    country: 'Global',
    trendingDate: '2023-07-25',
    tags: ['barbie', 'photorealistic', 'fashion', 'pink'],
  },
  {
    id: 'viral-006',
    promptText: 'An 80s-style yearbook photo. The photo should have a soft, hazy filter, feathered hair, retro clothing (like a denim jacket or a sweater with geometric patterns), and a laser grid background.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'TikTok',
    country: 'USA',
    trendingDate: '2024-01-30',
    tags: ['yearbook', 'retro', '80s', 'portrait'],
  },
  {
    id: 'viral-007',
    promptText: 'Generate a Lego version of a famous historical figure or movie character, placed in an iconic scene made entirely of Lego bricks. The lighting should be dramatic, and the focus should be sharp to show the detail of the plastic bricks.',
    category: 'Viral Trends',
    targetModel: 'DALL-E 3',
    platform: 'Facebook',
    country: 'UK',
    trendingDate: '2024-04-12',
    tags: ['lego', 'minifigure', 'diorama', 'pop culture'],
  },
  {
    id: 'viral-008',
    promptText: 'A charming claymation-style character, looking a bit wonky and handmade, sitting at a table eating a bowl of cereal. Soft, studio lighting, shallow depth of field, fingerprints visible on the clay.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Reddit',
    country: 'Global',
    trendingDate: '2023-10-22',
    tags: ['claymation', 'stop motion', 'aardman', 'character'],
  },
  {
    id: 'viral-009',
    promptText: 'A custom Funko Pop vinyl figure of a famous movie character, in its original packaging. The box has custom art and the character\'s name. Studio lighting, product shot, hyperrealistic.',
    category: 'Viral Trends',
    targetModel: 'DALL-E 3',
    platform: 'Facebook',
    country: 'USA',
    trendingDate: '2024-02-18',
    tags: ['funko pop', 'collectible', 'product design', 'pop culture'],
  },
  {
    id: 'viral-010',
    promptText: 'Create a self-portrait in the style of a Grand Theft Auto V loading screen character. Use bold, stylized illustrations with thick outlines, vibrant colors, and a dynamic pose against an iconic Los Angeles-style backdrop (like a beach or downtown).',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'TikTok',
    country: 'Global',
    trendingDate: '2023-09-05',
    tags: ['gta', 'video game', 'illustration', 'portrait'],
  },
  {
    id: 'viral-011',
    promptText: 'A knolling photograph of a deconstructed cheeseburger. All ingredients (bun, patty, cheese, lettuce, tomato, pickles, onions) are laid out flat in a perfect grid on a clean, solid color background. Top-down view, perfect 90-degree angles.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Instagram',
    country: 'Global',
    trendingDate: '2024-05-01',
    tags: ['knolling', 'flat lay', 'food photography', 'organization'],
  },
  {
    id: 'viral-012',
    promptText: 'An image of a character in the style of a gritty PlayStation 2 game cover from the early 2000s. Low-poly graphics, slightly blurry textures, dramatic and moody lighting, with a nostalgic \'PS2\' logo in the corner.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v5',
    platform: 'Reddit',
    country: 'Global',
    trendingDate: '2023-12-15',
    tags: ['ps2', 'retro gaming', 'nostalgia', 'game art'],
  },
  {
    id: 'viral-013',
    promptText: 'A still frame from a 90s family sitcom. The image should have a soft, slightly grainy 4:3 aspect ratio look. Characters are wearing dated fashion (big sweaters, mom jeans) and are in a cozy, over-decorated living room set. Warm, soft lighting.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'TikTok',
    country: 'USA',
    trendingDate: '2024-06-11',
    tags: ['90s', 'sitcom', 'retro', 'nostalgia'],
  },
  {
    id: 'viral-014',
    promptText: 'A two-color Risograph print of a botanical illustration. Use a limited color palette (e.g., fluorescent pink and blue), grainy textures, and slight misregistration artifacts typical of Riso printing. The style should be bold and graphic.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Instagram',
    country: 'UK',
    trendingDate: '2024-03-05',
    tags: ['risograph', 'printmaking', 'graphic design', 'illustration'],
  },
  {
    id: 'viral-015',
    promptText: 'A sweeping landscape view of a famous landmark (like the Eiffel Tower or the Taj Mahal) completely rebuilt in the blocky, voxel style of Minecraft. The sun should be setting, casting long, blocky shadows. Rendered in a realistic style.',
    category: 'Viral Trends',
    targetModel: 'DALL-E 3',
    platform: 'Reddit',
    country: 'Global',
    trendingDate: '2023-06-28',
    tags: ['minecraft', 'voxel art', 'gaming', 'landscape'],
  },
  {
    id: 'viral-016',
    promptText: 'A hyperrealistic, vibrant photograph of a spectacular float from the Rio Carnival. The image should capture the energy of the parade with dancers in elaborate costumes, confetti in the air, and dynamic, colorful lighting at night.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Instagram',
    country: 'Brazil',
    trendingDate: '2024-02-13',
    tags: ['carnival', 'rio', 'photorealistic', 'festival'],
  },
  {
    id: 'viral-017',
    promptText: 'A dramatic, high-contrast still frame from a 90s Brazilian telenovela. The image should feature two characters in a tense emotional moment, with classic 90s hairstyles and fashion. The lighting is dramatic and the colors are slightly faded.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Facebook',
    country: 'Brazil',
    trendingDate: '2023-10-18',
    tags: ['telenovela', 'retro', 'drama', '90s'],
  },
  {
    id: 'viral-018',
    promptText: 'Design a vintage, hand-painted Bollywood movie poster from the 1970s. It should feature dramatic illustrations of the main characters, bold, stylized typography for the film title, and a rich, colorful palette.',
    category: 'Viral Trends',
    targetModel: 'DALL-E 3',
    platform: 'Instagram',
    country: 'India',
    trendingDate: '2023-11-20',
    tags: ['bollywood', 'vintage', 'movie poster', 'illustration'],
  },
  {
    id: 'viral-019',
    promptText: 'A photorealistic image capturing the "cottagecore" aesthetic. A cozy, ivy-covered stone cottage in the English countryside, with a wildflower garden, a warm cup of tea on a rustic table, and soft, golden hour lighting.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Instagram',
    country: 'UK',
    trendingDate: '2023-09-10',
    tags: ['cottagecore', 'aesthetic', 'cozy', 'countryside'],
  },
  {
    id: 'viral-020',
    promptText: 'Create a spooky but cute character portrait in the distinct style of Tim Burton. The character should have large, expressive eyes, a stitched-together look, and be set against a dark, whimsical, gothic background.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'TikTok',
    country: 'USA',
    trendingDate: '2023-10-25',
    tags: ['tim burton', 'gothic', 'halloween', 'character design'],
  },
  {
    id: 'viral-021',
    promptText: 'A heroic, comic-book style illustration of a legendary Brazilian football player celebrating a goal. Dynamic action lines, dramatic shading, and the player is wearing the iconic yellow and green national team kit.',
    category: 'Viral Trends',
    targetModel: 'Midjourney v6',
    platform: 'Facebook',
    country: 'Brazil',
    trendingDate: '2024-06-25',
    tags: ['football', 'comic book', 'illustration', 'sports'],
  },
];
